### ISSUE TITLE
Total play time format error

### ISSUE THREAD

**Issue by katorlybot** [katorlys/Starlin_L2#1]
### Bug Information
**Describe the bug**
Player's total play time is expected to be a number with one decimal place, but the actual config generated has more decimals.

**Your operating environment**
- Operating system and its version: Windows Server 2012
- Programming language and its version: Minecraft Paper-1.18.1-82
- Dependencies and their versions: none

**Steps to Reproduce**

1. Simply make the plugin counts player's total play time.
2. See the config after several minutes.

**Expected behavior**
timedata.yml:
```yaml
d94a****-****-****-****-****f812****:
  name: E******m
  first-time: 2022.01.17 20:47
  total: 1.4
```

**Actual behavior**
timedata.yml:
```yaml
d94a****-****-****-****-****f812****:
  name: E******m
  first-time: 2022.01.17 20:47
  total: 1.4000000000000001
```

**Other**

### Agreement

- [x] I have read the Guidelines above and confirm I am following them with this report.
